name: Upload to pypi.org

on:
  # Triggers the workflow when a release is created
  release:
    types: [created]

  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Install Python
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Installs and upgrades pip and the build dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install .[dev]

      - name: Build and Upload to PyPI
        run: |
          python3 -m build
          python3 -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_TOKEN }}
